- 
  name: Start lighttpd # 
  hosts: webserver
  tasks:
    - name: Trying to ping the server
      ansible.builtin.ping:

    # - name: Install lighttpd
    #   apt:
    #     name: lighttpd
