- 
  name: Start lighttpd # 
  hosts: webserver
  become: yes
  tasks:
    - name: Trying to ping the server
      ansible.builtin.ping:
    - name: Install lighttpd
      apt:
        name: lighttpd
    - name: Start lighttpd
      ansible.builtin.systemd:
        state: started
        name: lighttpd

